name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Maven build & test
        run: >-
          mvn clean verify
          -Pcoverage
          --no-transfer-progress
          -DrepoToken=${COVERALLS_REPO_TOKEN}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Coveralls Coverage Report Submission
        run: >-
          mvn
          -Pcoverage
          --no-transfer-progress
          -DrepoToken=${COVERALLS_REPO_TOKEN}
          coveralls:report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
