name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Maven build & test
        run: >-
          mvn
          -Pcoverage
          clean verify
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Coveralls Coverage Report Submission
        run: >-
          mvn
          -Pcoverage
          coveralls:report
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
