name: build

on:
  push:
    branches:
      - feature/**
      - feat/**
      - hotfix/**
      - fix/**
      - dependabot/**
      - master

jobs:
  build:

    runs-on: [self-hosted, Linux]

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Maven build & test
        run: >-
          mvn clean verify
          -Pcoverage
          --batch-mode --no-transfer-progress -Dsilent=true

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: always()

      - uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
