name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Lint
        run: >-
          npx @redocly/cli lint

      - name: Maven build
        run: >-
          mvn clean verify
        env:
          GITHUB_TOKEN: ${{ github.token }}
