name: build

on:
  push:
    branches:
      - feature/**
      - feat/**
      - hotfix/**
      - fix/**
      - dependabot/**
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Maven build & test
        run: >-
          mvn clean verify
          -Pcoverage
          --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}
